version: '3'

services:
  server:
    build:
      context: ./server
      args:
        REACT_APP_HOST: ${DOMAIN:-xplosion}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.xplosion_api.loadbalancer.server.port=3000"
      - "traefik.http.routers.xplosion_api.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.xplosion_api.tls=true"
      - "traefik.http.routers.cc_api.rule=Host(`${DOMAIN:-xplosion.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api.stripprefix.prefixes=/api"
      - "traefik.http.routers.cc_api.middlewares=strip_api"
    networks:
      - traefik_web

  web:
    build:
      context: ./web
      args:
        REACT_APP_HOST: ${DOMAIN:-xplosion}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.xplosion.loadbalancer.server.port=3000"
      - "traefik.http.routers.xplosion.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.xplosion.rule=Host(`${DOMAIN:-xplosion.localhost}`)"
      - "traefik.http.routers.xplosion.tls=true"
    networks:
      - traefik_web


networks:
  traefik_web:
    external:
      true